language: node_js
node_js:
  - "10.0"
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - "npm i -g gatsby-cli"
script:
  - "npm test"
  - "gatsby build"
after_success:
  - "npm deploy"