name: Gatsby Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.10.0'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install -g gatsby-cli
          npm ci
        env:
          NODE_OPTIONS: --no-warnings

      - name: Build
        env:
          NODE_ENV: production
          GATSBY_ACTIVE_ENV: production
          NODE_OPTIONS: --no-warnings
        run: gatsby build --prefix-paths

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public